Task02
shagovAlexei/exadel-python-course-2021 pull request #6
Opened 2021-09-18 19:00 UTC by shagovAlexei

edit Task02

2021-09-19 19:02 UTC, ahodkov requested changes

2021-09-19 19:02 UTC, ahodkov commented on tasks/task02/triangle.py
> +        f = float(s)
I don't found any information about float. And in the example used integer.

2021-09-19 19:02 UTC, ahodkov commented on tasks/task02/triangle.py
> +    if len(parts) == 2:
`if len(parts) == 2 and check_positive(parts[0]) and check_positive(parts[1]):`

2021-09-19 19:02 UTC, ahodkov commented on tasks/task02/triangle.py
> +    if len(parts) == 3:
same

2021-09-19 19:02 UTC, ahodkov commented on tasks/task02/triangle.py
> +        print("""
`menu='''
    Menu:
    1. Calculate triangle area by base and height
    2. Calculate triangle area by 2 sides and angle between them
    3. Exit
    '''`
`print(menu)`

2021-09-19 19:02 UTC, ahodkov commented on tasks/task02/triangle.py
> +        elif menu_number != "":
`else:`

2021-09-19 19:02 UTC, ahodkov commented on tasks/task02/triangle.py
> +    while menu_number:
`menu_number != 3`

2021-09-19 19:02 UTC, ahodkov commented on tasks/task02/triangle.py
> +        menu_number = input("Enter menu item number: ")
`menu_number = int(input("Enter menu item number: "))`

2021-09-19 19:02 UTC, ahodkov commented on tasks/task02/triangle.py
> +            exit(0)
if use `menu_number != 3` exit(0) doesn't need

2021-09-26 15:21 UTC, closed without merging

2021-09-26 15:22 UTC, shagovAlexei commented
conflict